micronaut:
  application:
    name: demo
  server:
    port: 8081
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    dialect: H2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    schema-generate: CREATE
    password: ''
jpa:
  default:
    entity-scan:
      packages: 'es.serquo.micronaut.models'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:database

